### ISSUE TITLE
Your github pages are down

### ISSUE THREAD

**Issue by Bananeweizen** [netceteragroup/quickrex#4]
http://netceteragroup.github.io is down, and therefore also the update site of the plugin is not reachable.

**Comment by marschall** [comment]
Indeed it is.

**Comment by marschall** [comment]
Can you check again? It's a bit confusing because http://netceteragroup.github.io/quickrex/updatesite/ gives you a 404. But that's merely because we don't have an index file in that folder. Eclipse doesn't use the index file but the `artifacts.jar` and `content.jar` files which are there.

If I enter http://netceteragroup.github.io/quickrex/updatesite/ into Eclipse (e.g. Help -> Install New Software...) it works as an update site.

**Comment by Bananeweizen** [comment]
Looks good. Worked fine in an Oomph installation of mine.
